const data = {
  pageSize: { width: 500, height: 500, unit: 0 },
  background: {
    backgroundType: 0,
    colorType: 0,
    color1: "#ffffff",
    gradientColor1: "#dabc89",
    gradientColor2: "#b5945e",
    gradientAngle: 0,
    gradientStart: 0,
    gradientEnd: 1,
    imageType: 0,
    isTransparent: true,
    resourceType: "public",
  },
  graphs: [
    {
      graphType: "Text",
      angle: 0,
      opacity: 1,
      relativeRect: { x: 0.15656642804827003, y: 0.5883082706766909, width: 0.6857518310546875, height: 0.13959375 },
      resourceType: "public",
      isUpperCase: true,
      fontName: "Dosis",
      fontSize: 52,
      fontStyle: "normal",
      fontWeight: "normal",
      fontColor: "#000000",
      outline: false,
      glow: false,
      underline: false,
      textAlign: "center",
      text: "Company Name",
      lineHeight: 1,
      letterSpacing: 0,
      shadowOffset: 5,
      shadowAngle: 110,
      shadowOpacity: 60,
      curve: 0,
      shadow: false,
      shadowColor: "#000000",
      shadowBlur: 10,
    },
  ],
};

console.log(JSON.stringify(data));
